# Generated by Django 3.1.4 on 2021-04-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharedCart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
    ]
